### ISSUE TITLE
Registering Service is rather slow

### ISSUE THREAD

**Issue by schulz-m** [jmdns/jmdns#144]
We are currently evaluating different ZeroConfiguration Libraries and functionality-wise `jmdns` works rather nicely. But a big caveat is that the Service registering takes around 7 - 8 seconds, whereas with other libraries it seems to be well under a second. The culprit seems to be in the `waitForAnnounced` calls inside the [`registerService`](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/JmDNSImpl.java#L997) methods. Now I do understand that for a truly "save registering", you have to check if the service was announced in between, but why does it take so much longer than listening to existing Services with `ServiceListener`?

Any hints and explanations would be appreciated, especially in comparison to other mDNS/DNS-SD libraries out there :-)

We are using `jmdns` version `3.5.2` installed with maven.

**Comment by mustafasezgin** [comment]
Im seeing this too on Android. Registering a service takes a fair while. Did you end up finding a solution to this @schulz-m ?

**Comment by schulz-m** [comment]
@mustafasezgin Unfortunately we still haven't had time to look into this, will definitely keep it updated once we could!

**Comment by cschneider** [comment]
I experimented a bit with this. 

It seems the main wait (~5s) happens when we do:
this.waitForAnnounced(DNSConstants.SERVICE_INFO_TIMEOUT);
Here it waits until the jmsDNS instance itself is announced.  I suspect that we somehow miss the first announce on start and then must wait until DNS announces itself again.

The other wait is after we register our service (~2S):
info.waitForAnnounced(DNSConstants.SERVICE_INFO_TIMEOUT);
Not sure why this takes so long.

I found two ways to make jmdns faster. 
The first is to remove the two waits in JmDNSImpl.registerService. The disadvantage is of course that we are not sure the service is announced but for me that would not be a problem. I am not sure though if this affects other parts of the system. 

The second way I found is to remove only 
this.waitForAnnounced(DNSConstants.SERVICE_INFO_TIMEOUT);
and put it into create.  This also speeds up the process a lot.

So my question is: Can we safely remove the waits? What purpose do they serve?

**Comment by ViToni** [comment]
Both timeouts mentioned seem to be way too high. [RFC - Section 8.1](https://tools.ietf.org/html/rfc6762#section-8.1) describes the probing step to be complete (when no conflicts arise) after about 750ms.

**Comment by kaikreuzer** [comment]
@ViToni Is this really the feature we are looking at? The spec says that it should probe before it announces address records by itself, but the code seems to check whether it can find announcements for its own services after registering them. Or do I misinterpret the code?

**Comment by ViToni** [comment]
@kaikreuzer I haven't checked the code itself. Just thought how registering a service _should_ work according to the spec:

For a service to be registered I would expect these prerequisites to be sucessfully fullfilled
1. Probing
2. Announcing (after succesful Probing) => regsitration completed

The probing step takes about 0-250ms + 3x 250ms (so at most 1000ms) to be succesful but could fail earlier. When an mDNS service is registered dynamically (the mDNS service is already up for some time) the random offset fof 0-250ms might be omitted so it would be even faster.

As said: didn't check the code but the timeouts seem too high and waiting for its own service doesn't seems correct either (but this is a different story).
