### ISSUE TITLE
Service is resolving without a hostname

### ISSUE THREAD

**Issue by jcgoforth** [jmdns/jmdns#164]
In 3.5.4, on the service discovery side the service can become resolved without a hostname in the ServiceInfo (getServer() returns "").

The underlying issue is that the service is becoming resolved without ever receiving a SRV record. Additionally, even if it does receive the SRV record the hostname of the service ends up being dropped before the service becomes resolved.

**Comment by jcgoforth** [comment]
I have a fix for this, but I am completely new to git and I am working on getting everything setup correctly for the pull request.

**Comment by stef02** [comment]
can you please tell me about the fix?

**Comment by senft** [comment]
Are there any updates on this? I am currently experiencing the same problem.

**Comment by jcgoforth** [comment]
I dropped the ball on getting the pull request completed. I keep meaning to get back to it, I will try to get back to it this soon. In the mean time, this issue is fixed on my branch (https://github.com/jcgoforth/jmdns). I have been using a build of that code for the last 7 months without issue.

**Comment by senft** [comment]
Thanks @jcgoforth, I will have a look at your fork.

**Comment by janossch** [comment]
@kaikreuzer Imho this issue can be closed, since there is a closed PR specifically to this issue https://github.com/jmdns/jmdns/pull/165

@jcgoforth If you edit your main comment in your PR (https://github.com/jmdns/jmdns/pull/165), and you add the following line `Fix #164` as the first line it will link this PR with the ticket.
