### ISSUE TITLE
Warning level logs from DNSIncoming.readAnswer method

### ISSUE THREAD

**Issue by janossch** [jmdns/jmdns#282]
Dear Maintainers of JmDNS library,

Recently we came across a strange issue, and what happened is that time to time huge multiline messages started to appear in our log (attached [jmdns_log.txt](https://github.com/user-attachments/files/16596319/jmdns_log.txt)). 

There were warning level messages from DNSIncoming.readAnswer, [here](https://github.com/jmdns/jmdns/blob/f6d37e369cde11dd23b52341ec3f4f50c704640f/src/main/java/javax/jmdns/impl/DNSIncoming.java#L304) and from [here](https://github.com/jmdns/jmdns/blob/f6d37e369cde11dd23b52341ec3f4f50c704640f/src/main/java/javax/jmdns/impl/DNSIncoming.java#L309).
One could argue whether such huge message is necessary in a warning level log, but thats a [different question](https://github.com/jmdns/jmdns/issues/229).

I honestly don't know the reason why it was written out. **Is the message out of standard?**
The only piece of information what I could grasp here is the type of the service __dosvc._tcp.local._

Probably this is part of the [Delivery Optimization service](https://learn.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization) of Windows. Maybe I'm wrong, but to me it seems it is a recent development in Windows systems which uses DNS-based service discovery.

Quote from https://learn.microsoft.com/hu-hu/windows/deployment/do/whats-new-do#windows-11-22h2
_"New setting: Local Peer Discovery ..."_

There is another message in the log about "Bad domain name", but the machine - from which the messages are coming - is only part of a workgroup (and not of a domain).

I'm out of ideas. **Do you have any suggestion?**

**Comment by ViToni** [comment]
Hi @janossch,
I'm not a maintainer but maybe I can shed some light on the issue at hand.

The log messages you see are due to JmDNS only supporting a subset of resource record (RR) types (for the full list see: https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4 ).
The RR type indicates what kind of structure to expect for the next few bytes, basically how to read the data, e.g. IPv4, IPv6, a domain name, etc.
I've seen similar warning messages e.g. when Apple devices are present in the network as Apple makes use of RR type 65 which is rather new (registered in 2020) and supportfor RR tpye 65 hasn't been implemented (yet).
Unfortunately the actual RR type, which is not supported, is not logged in this case.
As of now there is no easy way to ignore specific RR types to be logged. I'm sure a PR for this would be welcome ;)

I couldn't find any occurences for `Could not find record class` in the attached logs. This one would be really exceptional as I would expect all records to have either class IN or ANY as the other ones were for uncommon network types (see: https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-2) I wouldn't expect to be present on your side. If such messages opspup I'd would rather think there is a buggy mDNS implmentation in your network (but most implementations I've seen use a fixed value for CLASS, so do not allow any deviations).

**Comment by janossch** [comment]
Hi @ViToni  

First of all thank you for trying to give some hints. Much appreciated! 
Obviously I have plenty of logs, but - in my perspective - it contains a lot of 'noise' thus I've missed to include that part...
I've just attached a similar log, but from a different day. [jmdns_log_2.txt](https://github.com/user-attachments/files/16610899/jmdns_log_2.txt)

from DNSRecordClass it has a message like this:
> Could not find record class for index: 65535

from DNSIncoming:
>  Could not find record class. domain:  type: TYPE_IGNORE index 0

**Comment by ViToni** [comment]
Hi @janossch,

hope all the information is useful in a way. Here is some more background🫣 which might explain why you see the all these logs:

DNS messages are made out of "questions" and "answers" (see: https://www.rfc-editor.org/rfc/rfc1035.html#section-4.1), 
DNS resource records (answers) are usually structured as described in https://www.rfc-editor.org/rfc/rfc1035.html#section-3.2.1 expect when they aren't e.g. for OPT records (maybe others as well, which I'm not aware of) which can be understood as an extension mechanism (see: https://www.rfc-editor.org/rfc/rfc6891.html#section-6.1.2)
As OPT seems to be supported in a way, I'd assume the issue to be any of the newer ones.

If you would like to solve the issue with a PR, my suggestion would be a 4-step program ;) :

1. Change https://github.com/jmdns/jmdns/blob/f6d37e369cde11dd23b52341ec3f4f50c704640f/src/main/java/javax/jmdns/impl/DNSIncoming.java#L302-L305 to log the actual value on the wire WITHOUT the full DNS message but WITH the domain (as it indicates who sends these records). This change would also make the actual type available (could be used for step 4.)
2. The same goes for the record class (although this one might be less important since IMO it is a result of unknown/unsupported type).
3. Skip the switch statement if the type is not known but take care to consume the bytes as in https://github.com/jmdns/jmdns/blob/f6d37e369cde11dd23b52341ec3f4f50c704640f/src/main/java/javax/jmdns/impl/DNSIncoming.java#L311-L313 and https://github.com/jmdns/jmdns/blob/f6d37e369cde11dd23b52341ec3f4f50c704640f/src/main/java/javax/jmdns/impl/DNSIncoming.java#L475-L478 otherwise it might break the offsets within the DNS message.
The log messages in https://github.com/jmdns/jmdns/blob/f6d37e369cde11dd23b52341ec3f4f50c704640f/src/main/java/javax/jmdns/impl/DNSIncoming.java#L303-L305 and https://github.com/jmdns/jmdns/blob/f6d37e369cde11dd23b52341ec3f4f50c704640f/src/main/java/javax/jmdns/impl/DNSIncoming.java#L475-L478 are somehow redundant so skipping one might help with the excessive logging.
4. This step is optional, but would help keeping your logs sane:
   1. Add a "reporter" interface which can be used to decide if an unknow type shall be logged or not.
   2. Make it optional to use for backward compatibility.
   3. Implement this interface which takes specifically care of the value within your network (as part of your configuration)
   4. One might want to be restrictive what to NOT log to see if new unknowns get introduced over time.

Not sure if my answer helps you as there is no out-of-the-box solution but if you'd like some feedback on an eventual PR feel free to ping me.

**Comment by ViToni** [comment]
For the review of #282 I took one more look at your logs. Your logs could also point to a "broken" device in your network, broken in a way that it's mDNS implmentation produces garbage, similar to https://github.com/jmdns/jmdns/blob/a0eda7fadfcf678f77c7e2bda320387bb60e40e5/src/main/java/javax/jmdns/impl/DNSIncoming.java#L318-L328

The change would reduce clutter in the logs but unfortunately the "broken" device would still spam your logs.

**Comment by janossch** [comment]
I would separate two things here: 
1. A broken (external) implementation somehow messes up the log
2. _JmDNS_ doesn't support the incoming message and this makes the log larger

In this particular case I believe we are facing the latter and - if I would be a maintainer - I would sacrifice 1-2 duplicate lines of log (per _DNS_ message) for the sake of a more readable log. Nevertheless I totally agree with the argument that even the duplicate log entries have to leave behind some traces for further investigations. Regarding the first point, one has the possibility to enable _DEBUG_ level logging (if interested in finding the root cause of a broken implementation) as it is resulting in a similar looking log as it was before the PR...

BUT,

@ViToni I've just gone through again the code around logging and I believe I found something which as well makes these logs even larger.

If you take a closer look on `DNSIncoming.print(boolean dump)`, you can see that all _questions_, _answers_, _additionals_, etc. are written out twice, because
1. `DNSIncoming.print(boolean dump)` internally calling `DNSMessage.print()` then 
2. the base class calling the `DNSIncoming.toString` instance method, which ends up here in the derived class:

https://github.com/jmdns/jmdns/blob/a0eda7fadfcf678f77c7e2bda320387bb60e40e5/src/main/java/javax/jmdns/impl/DNSIncoming.java#L559-L565

After the `DNSIncoming.toString()` returns the abstract base class continues calling the following instructions here:

https://github.com/jmdns/jmdns/blob/a0eda7fadfcf678f77c7e2bda320387bb60e40e5/src/main/java/javax/jmdns/impl/DNSMessage.java#L260-L264

As you can see DNS entries (_questions_, _answers_, _additionals_, etc.) are logged twice. They are just different in their format e.g.:

```
...
answers:
	[Pointer@659194318 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _dosvc._tcp.local. ttl: '4499/4500' alias: 'OFFICEPC(1)._dosvc._tcp.local.']
...
```
and a little bit later in the log:

```
...
	answer:        [Pointer@659194318 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _dosvc._tcp.local. ttl: '4499/4500' alias: 'OFFICEPC(1)._dosvc._tcp.local.']
...
```
