### ISSUE TITLE
Crash on Android 14

### ISSUE THREAD

**Issue by FFelt** [jmdns/jmdns#287]
In rare cases jmDNS crashes on Android 14 devices. I can't reproduce it consistently. But it happens from time to time.

The stacktrace from the crash is:

```
java.util.concurrent.RejectedExecutionException:Taskjava.util.concurrent.FutureTask@dca[Notcompleted]rejectedfromjava.util.concurrent.ThreadPoolExecutor@43a[Terminated,poolsize=0,activethreads=0,queuedtasks=0,completedtasks=185]
atjava.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
atjava.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
atjava.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
atjava.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
atjava.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:705)
atjavax.jmdns.impl.JmDNSImpl.updateRecord(JmDNSImpl.java:1324)
atjavax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1461)
atjavax.jmdns.impl.JmDNSImpl.handleQuery(JmDNSImpl.java:1583)
atjavax.jmdns.impl.SocketListener.run(SocketListener.java:75)
```

For me it looks like the Threadpool is already terminated because probably the close-method in https://github.com/jmdns/jmdns/blob/main/src/main/java/javax/jmdns/impl/JmDNSImpl.java was called before, which shuts down the executor.

Does anyone else have this problem? In my case in only occurs on Android 14 devices, other Android versions seem to be unaffected.

Thanks in advance for any help or hints.

PullRequest with possible solution: https://github.com/jmdns/jmdns/pull/288/

**Comment by janossch** [comment]
Hi, I'm a newbie here, but I believe the modifications in the [PR](https://github.com/jmdns/jmdns/pull/288) won't solve your issue. Maybe it will lower the frequency of its occurrence, and cure its symptoms, but if at least one thread somehow _escapes_ from that `if` condition (since it is not synchronized), you could still face this problem. I think the only way to avoid the crash is to catch the `RejectedExecutionException` thrown by `submit`.

Additionally, by looking how JmDNS closes itself, I believe closing the `_socket` first and then shutting down the `_executor` would be a good idea. This way no more incoming message could generate tasks for the `_executor`, i.e.: flip these two lines: 
https://github.com/jmdns/jmdns/blob/3499b05b21377c9f7db9de6cd5422d90c69c78c7/src/main/java/javax/jmdns/impl/JmDNSImpl.java#L1965-L1969

But let's hear other opinions as well. :)

**Comment by FFelt** [comment]
Hey janossch,
Thanks for your suggestions :)
I updated the PR and changed the things you mentioned.

Further hints and suggestions are welcome :)
