### ISSUE TITLE
Consider using `java.util.logging` instead of SLF4J

### ISSUE THREAD

**Issue by gastaldi** [jmdns/jmdns#290]
This will make this library require zero dependencies during run time.

**Comment by gastaldi** [comment]
SLF4J was introduced in https://github.com/jmdns/jmdns/pull/47, what was the motivation @kaikreuzer? The PR doesn't explain why

**Comment by ViToni** [comment]
I kindly disagree. IMHO slf4j is the de facto interface for logging, so that users can freely decide on their logging framework.

Switching back to ˋjulˋ would be

- A breaking change
- Introduce a dependency for people who use something else than ˋjulˋ
- Using a different ˋLogManagerˋ involves AFAIR setting a system property which might be an even bigger change (depending on the specific deployment) as one cannot use a different JAR as a drop-in replacement

**Comment by janossch** [comment]
Not strictly connected to this topic .. but I think it would be a good idea to add a logging implementation for the tests, i.e:

```
<dependency>
	<groupId>ch.qos.logback</groupId>
	<artifactId>logback-classic</artifactId>
	<version>1.3.14</version>
	<scope>test</scope>
</dependency>
```

or any other logging framework. Strictly with `test` scope. What do you think? Should I raise a separate '_issue_' for this?

**Comment by gastaldi** [comment]
> I kindly disagree. IMHO slf4j is the de facto interface for logging, so that users can freely decide on their logging framework.

JUL isn't perfect, but it pays off for not requiring any external dependencies, which is really important when providing a library.

> 
> Switching back to ˋjulˋ would be
> 
> * A breaking change

No, the Logging API isn't exposed so no API changes are required, just the implementation.

> * Introduce a dependency for people who use something else than ˋjulˋ

That makes no sense to me, JUL is part of the JDK and doesn't introduce any new dependency

> * Using a different ˋLogManagerˋ involves AFAIR setting a system property which might be an even bigger change (depending on the specific deployment) as one cannot use a different JAR as a drop-in replacement

Again, we're talking about a library here, you can still use SL4J in your application and have the logging output produced using JUL in the same place, without changing a single line of code.

**Comment by gastaldi** [comment]
> Not strictly connected to this topic .. but I think it would be a good idea to add a logging implementation for the tests, i.e:
> 
> ```
> <dependency>
> 	<groupId>ch.qos.logback</groupId>
> 	<artifactId>logback-classic</artifactId>
> 	<version>1.3.14</version>
> 	<scope>test</scope>
> </dependency>
> ```
> 
> or any other logging framework. Strictly with `test` scope. What do you think? Should I raise a separate '_issue_' for this?

Moving to JUL wouldn't require any new logging implementation dependency either, so I don't think that will be necessary if this is done

**Comment by janossch** [comment]
> Again, we're talking about a library here, you can still use SL4J in your application and have the logging output produced using JUL in the same place, without changing a single line of code.

Let's suppose I have an application which is using SLF4J and I'm using a library which is using JUL (JmDNS 3.4.2). 
What should I do in my application to have the library's log next to my application's log?

**Comment by gastaldi** [comment]
@janossch Ah I see your point. There are solutions like https://mvnrepository.com/artifact/org.slf4j/jul-to-slf4j to bridge the calls to the SLF4J API, but it depends on the the SLF4J logging implementation you use, but using the SLF4J API may be easier to avoid any extra work in this case (also maybe this was the motivation why it was changed in #47).

Anyway, feel free to close this issue.

**Comment by ViToni** [comment]
> > I kindly disagree. IMHO slf4j is the de facto interface for logging, so that users can freely decide on their logging framework.
> 
> JUL isn't perfect, but it pays off for not requiring any external dependencies, which is really important when providing a library.
> 

IMHO it doesn't. It's a PITA. There is a reason `slf4j` came to life. The only downside of `slf4j` is that now there are two major version 1.x and 2.x which might introduce conflicts based on the state of other libraries used. 

> > Switching back to ˋjulˋ would be
> > 
> > * A breaking change
> 
> No, the Logging API isn't exposed so no API changes are required, just the implementation.

It is for multiple reasons:

- Any tools used to analyse logs, would now have to deal with different names for log levels SEVERE, FINER, etc.
- If one uses other libraries in addition JmDNS one would have to set a different `LogManager`
  - One needs an additional JAR to bridge from `jul` to the loggin framework of choice
  - One needs to set the system property for the JVM so that the specific `LogManager` is used
  - If one happens to have software including JmDNS running on embedded devices one would not only have to update JARS but also the JVM settings, maybe even remotely.
- It's also fun to find a WARN / ERROR message and to remember search for `.severe` in the code...

> 
> > * Introduce a dependency for people who use something else than ˋjulˋ
> 
> That makes no sense to me, JUL is part of the JDK and doesn't introduce any new dependency
> 

Please read my words: 
> > for people who use something else than ˋjulˋ

Means any deployment which is NOT using `jul` as their default logging framework needs an additional JAR to bridge from `jul` to the logging framework of choice.

> > * Using a different ˋLogManagerˋ involves AFAIR setting a system property which might be an even bigger change (depending on the specific deployment) as one cannot use a different JAR as a drop-in replacement
> 
> Again, we're talking about a library here, you can still use SL4J in your application and have the logging output produced using JUL in the same place, without changing a single line of code.

As most libraries already include a dependecy to `slf4j` one wouldn't get anything out of it, expect when having JmDNS as the only dependency.
