### ISSUE TITLE
3.5.13-SNAPSHOT fails to compile test due to mismatch of JDK versions

### ISSUE THREAD

**Issue by ViToni** [jmdns/jmdns#324]
JmDNS make use of Mockito, specifically Mockito 5.2.0. However Mockito 5.x is supposed to run on JDK 11 or above.
When JmDNS is compiled with JDK 8 usage of Mockito fails due to this mismatch in JDK / class file versions:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project jmdns: Compilation failure
[ERROR] /Users/vtoni/git/jmdns/src/test/java/javax/jmdns/impl/DNSRecordTest.java:[19,19] cannot access org.mockito.Mockito
[ERROR]   bad class file: /Users/vtoni/.m2/repository/org/mockito/mockito-core/5.2.0/mockito-core-5.2.0.jar(org/mockito/Mockito.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR]
```

This issue could be solved by going back to Mockito 4.x (latest ATM is 4.11.0).

**Comment by janossch** [comment]
@ViToni You can use JDK17, as it is in the github workflow.

https://github.com/jmdns/jmdns/blob/9175588f5d7bf9db7b2ade60737262512919a3ac/.github/workflows/maven.yml#L27

As far as I understand JmDNS still targets JDK8, but it is compiled using JDK17. Since tests are not required to be compatible with JDK8, they can use newer versions of JDK.
