### ISSUE TITLE
JmDNS.close() blocks for a long period

### ISSUE THREAD

**Issue by nezen** [jmdns/jmdns#82]
I'm not sure if it's a problem, but JmDNS.close() takes about 6 seconds to finish, why does it take so long? What's going on?

**Comment by kaikreuzer** [comment]
Could you debug and find out yourself?

**Comment by mbeaty** [comment]
I'm seeing this too. How would you suggest debugging this? Where are the log messages that I see in the implementation classes going?

**Comment by mbeaty** [comment]
It's blocking for 5 seconds on this call. The constant is 5s.

            this.waitForCanceled(DNSConstants.CLOSE_TIMEOUT);

Looking at the code, I basically have no idea what is going on, as this call results in multiple layers of calls. Anyone have knowledge of what we're waiting to cancel here?

**Comment by kaikreuzer** [comment]
Not me, unfortunately...

**Comment by guillerodriguez** [comment]
Looking at the code for JmDNSImpl.close() I see the following:

 1. It first [calls closeState()](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/JmDNSImpl.java#L1866), which ends up calling closeState() on the _localHost object.
 This sets the internal state to DnsState.CLOSING: See [here](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/DNSStatefulObject.java#L279).
 2. Later it [calls waitForCanceled(..)](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/JmDNSImpl.java#L1880), which ends up calling waitForCanceled() on the _localHost object. This waits until state.isCanceled() returns true, or the timeout expires. See: [here](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/DNSStatefulObject.java#L402).
 3. But state.isCanceled() only returns true [if the state is DnsState is set to "canceled"](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/constants/DNSState.java#L193). Since this was set to "closing" in step 1, this check never succeeds. The call only returns after the 5 second timeout.

Either the logic seems to be wrong here or (could be perfectly the case) I am overlooking something.

**Comment by etyrrill** [comment]
@guillerodriguez, your analysis is correct.  It looks like the problem goes back to this [commit](https://github.com/jmdns/jmdns/commit/20f56757f932ed00a4c74bc75c73abd13b1a4c81) from seven years ago.

The close() method at this time was changed to call closeState() instead of cancelState(), but the code continues to waitForCanceled().

So for kicks I changed the [closeState()](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/JmDNSImpl.java#L1893) call back to cancelState(), and JmDNSImple.close() only takes about 2 seconds then.

Furthermore, the call to JmDNSImple.closeState() causes the state to change to closing, but the state never transitions to closed.  So even if JmDNSImple.close() was changed to wait for a closed state instead of canceled it would not fix the problem.  I believe the closing and closed state implementation simply wasn't finished, and possibly the best thing would be to revert back to the previous canceling logic.
