### ISSUE TITLE
Eclipse-related files should not be in the repository

### ISSUE THREAD

**Issue by rspielmann** [jmdns/jmdns#91]
The repository contains files like .project, .classpath and the .settings folder. Most, if not all, of those should not be part of the repository. Instead, configuration files that are specific to one distinct IDE should be generated, e.g. by tools like Maven, when the code is imported as a project.

**Comment by kaikreuzer** [comment]
Well, this is a regular topic of discussions and I think there is no right or wrong.
Projects that I maintain contain those files, since they are often not using Maven IDE integration due to different reasons. Therefore it is very convenient to have these files when working with Eclipse. For people using other IDEs, they should not harm.
